/**
 * 碗内食材主表。贴图固定放在微信分包：
 *   subpackages/bowl_core/assets/images/bowl/<fruitId>_1.png
 *   subpackages/bowl_core/assets/images/bowl/<fruitId>_2.png
 */
import { BOWL_CORE_IMAGES_ROOT } from '@/config/bowlAssets';

export const FRUIT_IDS = [
  'almond_slice',
  'apricot',
  'apple',
  'avocado',
  'banana',
  'basil_seed',
  'bayberry',
  'blackberry',
  'blackcurrant',
  'black_rice',
  'blueberry',
  'boba_pearl',
  'cantaloupe',
  'chestnut',
  'cherry',
  'cherry_tomato',
  'chocolate_chip',
  'cookie_crumb',
  'coconut_jelly',
  'cranberry',
  'cucumber',
  'crystal_jelly',
  'dragonfruit',
  'dried_longan',
  'durian',
  'emblic',
  'fig',
  'foxnut',
  'gooseberry',
  'grapefruit',
  'grape',
  'grape_green',
  'grass_jelly',
  'guava',
  'hawthorn',
  'honeydew',
  'kiwi',
  'kumquat',
  'lemon',
  'lime',
  'lily_bulb',
  'longan',
  'lotus_root',
  'lotus_seed',
  'lychee',
  'mandarin',
  'mango',
  'mangosteen',
  'marshmallow',
  'mini_mochi',
  'mint',
  'mulberry',
  'nectarine',
  'oat_flake',
  'orange',
  'osmanthus',
  'papaya',
  'passionfruit',
  'peach',
  'peach_gum',
  'pear',
  'peanut',
  'persimmon',
  'pineapple',
  'plum',
  'pop_boba',
  'pomegranate',
  'pudding_cube',
  'pumpkin_cube',
  'radish_heart',
  'raspberry',
  'red_bean',
  'red_date',
  'sago',
  'snow_fungus',
  'sour_plum',
  'starfruit',
  'strawberry',
  'sweet_potato',
  'taro_ball',
  'taro_dice',
  'water_chestnut',
  'walnut_piece',
  'watermelon',
  'wax_apple',
  'yangjiaomi_melon',
  'young_coconut',
  'ice_cube',
] as const;

export type FruitId = (typeof FRUIT_IDS)[number];

export interface FruitConfig {
  id: FruitId;
  label: string;
  color: number;
  /** 碗内 / 订单主展示用图 1 */
  asset: string;
  /** 碗内随机另一张图（与 asset 二选一） */
  bowlAsset2: string;
}

const bowl = (id: FruitId, slot: 1 | 2) => `${BOWL_CORE_IMAGES_ROOT}/bowl/${id}_${slot}.png`;

export const FRUIT_CONFIGS: FruitConfig[] = [
  { id: 'almond_slice', label: '杏仁片', color: 0xa66a2c, asset: bowl('almond_slice', 1), bowlAsset2: bowl('almond_slice', 2) },
  { id: 'apricot', label: '杏', color: 0xfb8c00, asset: bowl('apricot', 1), bowlAsset2: bowl('apricot', 2) },
  { id: 'apple', label: '苹果', color: 0xff8a65, asset: bowl('apple', 1), bowlAsset2: bowl('apple', 2) },
  { id: 'avocado', label: '牛油果', color: 0x8bc34a, asset: bowl('avocado', 1), bowlAsset2: bowl('avocado', 2) },
  { id: 'banana', label: '香蕉', color: 0xfdd835, asset: bowl('banana', 1), bowlAsset2: bowl('banana', 2) },
  { id: 'basil_seed', label: '兰香子', color: 0xd7ccc8, asset: bowl('basil_seed', 1), bowlAsset2: bowl('basil_seed', 2) },
  { id: 'bayberry', label: '杨梅', color: 0x7b1fa2, asset: bowl('bayberry', 1), bowlAsset2: bowl('bayberry', 2) },
  { id: 'blackberry', label: '黑莓', color: 0x7b1fa2, asset: bowl('blackberry', 1), bowlAsset2: bowl('blackberry', 2) },
  { id: 'blackcurrant', label: '黑加仑', color: 0x7b1fa2, asset: bowl('blackcurrant', 1), bowlAsset2: bowl('blackcurrant', 2) },
  { id: 'black_rice', label: '血糯米', color: 0x8d6e63, asset: bowl('black_rice', 1), bowlAsset2: bowl('black_rice', 2) },
  { id: 'blueberry', label: '蓝莓', color: 0x7b1fa2, asset: bowl('blueberry', 1), bowlAsset2: bowl('blueberry', 2) },
  { id: 'boba_pearl', label: '珍珠', color: 0xd7ccc8, asset: bowl('boba_pearl', 1), bowlAsset2: bowl('boba_pearl', 2) },
  { id: 'cantaloupe', label: '蜜瓜', color: 0x8bc34a, asset: bowl('cantaloupe', 1), bowlAsset2: bowl('cantaloupe', 2) },
  { id: 'chestnut', label: '栗子', color: 0xa66a2c, asset: bowl('chestnut', 1), bowlAsset2: bowl('chestnut', 2) },
  { id: 'cherry', label: '樱桃', color: 0xd32f2f, asset: bowl('cherry', 1), bowlAsset2: bowl('cherry', 2) },
  { id: 'cherry_tomato', label: '小番茄', color: 0xd32f2f, asset: bowl('cherry_tomato', 1), bowlAsset2: bowl('cherry_tomato', 2) },
  { id: 'chocolate_chip', label: '巧克力豆', color: 0x5d4037, asset: bowl('chocolate_chip', 1), bowlAsset2: bowl('chocolate_chip', 2) },
  { id: 'cookie_crumb', label: '饼干碎', color: 0xd7ccc8, asset: bowl('cookie_crumb', 1), bowlAsset2: bowl('cookie_crumb', 2) },
  { id: 'coconut_jelly', label: '椰果', color: 0xd7ccc8, asset: bowl('coconut_jelly', 1), bowlAsset2: bowl('coconut_jelly', 2) },
  { id: 'cranberry', label: '蔓越莓', color: 0xd32f2f, asset: bowl('cranberry', 1), bowlAsset2: bowl('cranberry', 2) },
  { id: 'cucumber', label: '黄瓜', color: 0x43a047, asset: bowl('cucumber', 1), bowlAsset2: bowl('cucumber', 2) },
  { id: 'crystal_jelly', label: '水晶果冻', color: 0xd7ccc8, asset: bowl('crystal_jelly', 1), bowlAsset2: bowl('crystal_jelly', 2) },
  { id: 'dragonfruit', label: '火龙果', color: 0xec407a, asset: bowl('dragonfruit', 1), bowlAsset2: bowl('dragonfruit', 2) },
  { id: 'dried_longan', label: '桂圆肉干', color: 0x8d6e63, asset: bowl('dried_longan', 1), bowlAsset2: bowl('dried_longan', 2) },
  { id: 'durian', label: '榴莲', color: 0xfdd835, asset: bowl('durian', 1), bowlAsset2: bowl('durian', 2) },
  { id: 'emblic', label: '油柑', color: 0x8bc34a, asset: bowl('emblic', 1), bowlAsset2: bowl('emblic', 2) },
  { id: 'fig', label: '无花果', color: 0x8d6e63, asset: bowl('fig', 1), bowlAsset2: bowl('fig', 2) },
  { id: 'foxnut', label: '鸡头米', color: 0x8d6e63, asset: bowl('foxnut', 1), bowlAsset2: bowl('foxnut', 2) },
  { id: 'gooseberry', label: '醋栗', color: 0x43a047, asset: bowl('gooseberry', 1), bowlAsset2: bowl('gooseberry', 2) },
  { id: 'grapefruit', label: '西柚', color: 0xfb8c00, asset: bowl('grapefruit', 1), bowlAsset2: bowl('grapefruit', 2) },
  { id: 'grape', label: '葡萄', color: 0x6a1b9a, asset: bowl('grape', 1), bowlAsset2: bowl('grape', 2) },
  { id: 'grape_green', label: '青提', color: 0x43a047, asset: bowl('grape_green', 1), bowlAsset2: bowl('grape_green', 2) },
  { id: 'grass_jelly', label: '烧仙草', color: 0xd7ccc8, asset: bowl('grass_jelly', 1), bowlAsset2: bowl('grass_jelly', 2) },
  { id: 'guava', label: '番石榴', color: 0x8bc34a, asset: bowl('guava', 1), bowlAsset2: bowl('guava', 2) },
  { id: 'hawthorn', label: '山楂', color: 0xd32f2f, asset: bowl('hawthorn', 1), bowlAsset2: bowl('hawthorn', 2) },
  { id: 'honeydew', label: '哈密瓜', color: 0x8bc34a, asset: bowl('honeydew', 1), bowlAsset2: bowl('honeydew', 2) },
  { id: 'kiwi', label: '猕猴桃', color: 0x43a047, asset: bowl('kiwi', 1), bowlAsset2: bowl('kiwi', 2) },
  { id: 'kumquat', label: '金桔', color: 0xfb8c00, asset: bowl('kumquat', 1), bowlAsset2: bowl('kumquat', 2) },
  { id: 'lemon', label: '柠檬', color: 0xfdd835, asset: bowl('lemon', 1), bowlAsset2: bowl('lemon', 2) },
  { id: 'lime', label: '青柠', color: 0x43a047, asset: bowl('lime', 1), bowlAsset2: bowl('lime', 2) },
  { id: 'lily_bulb', label: '百合', color: 0x8d6e63, asset: bowl('lily_bulb', 1), bowlAsset2: bowl('lily_bulb', 2) },
  { id: 'longan', label: '桂圆', color: 0x8d6e63, asset: bowl('longan', 1), bowlAsset2: bowl('longan', 2) },
  { id: 'lotus_root', label: '藕片', color: 0x80cbc4, asset: bowl('lotus_root', 1), bowlAsset2: bowl('lotus_root', 2) },
  { id: 'lotus_seed', label: '莲子', color: 0x8d6e63, asset: bowl('lotus_seed', 1), bowlAsset2: bowl('lotus_seed', 2) },
  { id: 'lychee', label: '荔枝', color: 0xd32f2f, asset: bowl('lychee', 1), bowlAsset2: bowl('lychee', 2) },
  { id: 'mandarin', label: '砂糖橘', color: 0xfb8c00, asset: bowl('mandarin', 1), bowlAsset2: bowl('mandarin', 2) },
  { id: 'mango', label: '芒果', color: 0xfdd835, asset: bowl('mango', 1), bowlAsset2: bowl('mango', 2) },
  { id: 'mangosteen', label: '山竹', color: 0x6a1b9a, asset: bowl('mangosteen', 1), bowlAsset2: bowl('mangosteen', 2) },
  { id: 'marshmallow', label: '棉花糖', color: 0xd7ccc8, asset: bowl('marshmallow', 1), bowlAsset2: bowl('marshmallow', 2) },
  { id: 'mini_mochi', label: '小糍粑', color: 0xd7ccc8, asset: bowl('mini_mochi', 1), bowlAsset2: bowl('mini_mochi', 2) },
  { id: 'mint', label: '薄荷', color: 0x43a047, asset: bowl('mint', 1), bowlAsset2: bowl('mint', 2) },
  { id: 'mulberry', label: '桑葚', color: 0x6a1b9a, asset: bowl('mulberry', 1), bowlAsset2: bowl('mulberry', 2) },
  { id: 'nectarine', label: '油桃', color: 0xfb8c00, asset: bowl('nectarine', 1), bowlAsset2: bowl('nectarine', 2) },
  { id: 'oat_flake', label: '燕麦', color: 0xd7ccc8, asset: bowl('oat_flake', 1), bowlAsset2: bowl('oat_flake', 2) },
  { id: 'orange', label: '橙子', color: 0xfb8c00, asset: bowl('orange', 1), bowlAsset2: bowl('orange', 2) },
  { id: 'osmanthus', label: '桂花干', color: 0xfdd835, asset: bowl('osmanthus', 1), bowlAsset2: bowl('osmanthus', 2) },
  { id: 'papaya', label: '木瓜', color: 0xfb8c00, asset: bowl('papaya', 1), bowlAsset2: bowl('papaya', 2) },
  { id: 'passionfruit', label: '百香果', color: 0x6a1b9a, asset: bowl('passionfruit', 1), bowlAsset2: bowl('passionfruit', 2) },
  { id: 'peach', label: '桃子', color: 0xfb8c00, asset: bowl('peach', 1), bowlAsset2: bowl('peach', 2) },
  { id: 'peach_gum', label: '桃胶', color: 0x8d6e63, asset: bowl('peach_gum', 1), bowlAsset2: bowl('peach_gum', 2) },
  { id: 'pear', label: '雪梨', color: 0xf6e7a8, asset: bowl('pear', 1), bowlAsset2: bowl('pear', 2) },
  { id: 'peanut', label: '花生碎', color: 0xa66a2c, asset: bowl('peanut', 1), bowlAsset2: bowl('peanut', 2) },
  { id: 'persimmon', label: '柿子', color: 0xfb8c00, asset: bowl('persimmon', 1), bowlAsset2: bowl('persimmon', 2) },
  { id: 'pineapple', label: '菠萝', color: 0xfdd835, asset: bowl('pineapple', 1), bowlAsset2: bowl('pineapple', 2) },
  { id: 'plum', label: '李子', color: 0x6a1b9a, asset: bowl('plum', 1), bowlAsset2: bowl('plum', 2) },
  { id: 'pop_boba', label: '爆爆珠', color: 0xd7ccc8, asset: bowl('pop_boba', 1), bowlAsset2: bowl('pop_boba', 2) },
  { id: 'pomegranate', label: '石榴', color: 0xd32f2f, asset: bowl('pomegranate', 1), bowlAsset2: bowl('pomegranate', 2) },
  { id: 'pudding_cube', label: '布丁', color: 0xd7ccc8, asset: bowl('pudding_cube', 1), bowlAsset2: bowl('pudding_cube', 2) },
  { id: 'pumpkin_cube', label: '南瓜块', color: 0xfdd835, asset: bowl('pumpkin_cube', 1), bowlAsset2: bowl('pumpkin_cube', 2) },
  { id: 'radish_heart', label: '红心萝卜丁', color: 0x80cbc4, asset: bowl('radish_heart', 1), bowlAsset2: bowl('radish_heart', 2) },
  { id: 'raspberry', label: '树莓', color: 0xd32f2f, asset: bowl('raspberry', 1), bowlAsset2: bowl('raspberry', 2) },
  { id: 'red_bean', label: '蜜红豆', color: 0xd7ccc8, asset: bowl('red_bean', 1), bowlAsset2: bowl('red_bean', 2) },
  { id: 'red_date', label: '红枣', color: 0xd32f2f, asset: bowl('red_date', 1), bowlAsset2: bowl('red_date', 2) },
  { id: 'sago', label: '西米', color: 0xd7ccc8, asset: bowl('sago', 1), bowlAsset2: bowl('sago', 2) },
  { id: 'snow_fungus', label: '银耳', color: 0x8d6e63, asset: bowl('snow_fungus', 1), bowlAsset2: bowl('snow_fungus', 2) },
  { id: 'sour_plum', label: '青梅', color: 0x8bc34a, asset: bowl('sour_plum', 1), bowlAsset2: bowl('sour_plum', 2) },
  { id: 'starfruit', label: '杨桃', color: 0xfdd835, asset: bowl('starfruit', 1), bowlAsset2: bowl('starfruit', 2) },
  { id: 'strawberry', label: '草莓', color: 0xd32f2f, asset: bowl('strawberry', 1), bowlAsset2: bowl('strawberry', 2) },
  { id: 'sweet_potato', label: '蜜红薯', color: 0xfdd835, asset: bowl('sweet_potato', 1), bowlAsset2: bowl('sweet_potato', 2) },
  { id: 'taro_ball', label: '芋圆', color: 0xd7ccc8, asset: bowl('taro_ball', 1), bowlAsset2: bowl('taro_ball', 2) },
  { id: 'taro_dice', label: '芋头丁', color: 0x8d6e63, asset: bowl('taro_dice', 1), bowlAsset2: bowl('taro_dice', 2) },
  { id: 'water_chestnut', label: '荸荠', color: 0x80cbc4, asset: bowl('water_chestnut', 1), bowlAsset2: bowl('water_chestnut', 2) },
  { id: 'walnut_piece', label: '核桃仁', color: 0xa66a2c, asset: bowl('walnut_piece', 1), bowlAsset2: bowl('walnut_piece', 2) },
  { id: 'watermelon', label: '西瓜', color: 0x43a047, asset: bowl('watermelon', 1), bowlAsset2: bowl('watermelon', 2) },
  { id: 'wax_apple', label: '莲雾', color: 0xd32f2f, asset: bowl('wax_apple', 1), bowlAsset2: bowl('wax_apple', 2) },
  { id: 'yangjiaomi_melon', label: '羊角蜜', color: 0x8bc34a, asset: bowl('yangjiaomi_melon', 1), bowlAsset2: bowl('yangjiaomi_melon', 2) },
  { id: 'young_coconut', label: '椰青块', color: 0x43a047, asset: bowl('young_coconut', 1), bowlAsset2: bowl('young_coconut', 2) },
  { id: 'ice_cube', label: '冰块', color: 0x9adcf2, asset: bowl('ice_cube', 1), bowlAsset2: bowl('ice_cube', 2) },
];

export const FRUIT_MAP = Object.fromEntries(
  FRUIT_CONFIGS.map((fruit) => [fruit.id, fruit]),
) as Record<FruitId, FruitConfig>;
